In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display

In [2]:
mp_key = "0DGGEC1I1pS8KvdIsdLZpSI8D4eSE7ux"
mp_id = "mp-648"

In [3]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id) 

conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure() 
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations() 



Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [4]:


print("visualisation du Na2S :")

view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('rotate on')



visualisation du Na2S :


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [9]:
# Symmetrie 1

i_atom1 = 7
i_symmop1 = 2

print("----- Symmétrie 1 : Atome de Na (index 7) ----- \n")

symmop1 = symmops[i_symmop1]
print(symmop1)

print("Les coordonnées initial de l'atome sont")
pos_init = conv_struc.sites[i_atom1 -1].frac_coords
print(pos_init,"\n")

print("Apres l'opération de symmétrie, ces coordonnées sont")
pos_final = symmop1.operate(pos_init)
print(pos_final,"\n")


print("La matrice de rotation est une matrice de rotation tridimensionnelle qui effectue une rotation de 90 degrés autour de l'axe c. Elle représente donc une symmétrie de rotation d'ordre 4 (C4).")



view1 = quick_view(conv_struc, "packed", conventional = True)
display(view1)


view1.script('draw SYMOP ' + str(i_symmop1 + 1) + ' {atomno = ' + str(i_atom1) + '}')


----- Symmétrie 1 : Atome de Na (index 7) ----- 

Rot:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Les coordonnées initial de l'atome sont
[0.75 0.75 0.25] 

Apres l'opération de symmétrie, ces coordonnées sont
[-0.75  0.75  0.25] 

La matrice de rotation est une matrice de rotation tridimensionnelle qui effectue une rotation de 90 degrés autour de l'axe c. Elle représente donc une symmétrie de rotation d'ordre 4 (C4).


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [19]:
# Symmetrie 2

i_atom2 = 3
i_symmop2 = 8

print("----- Symmétrie 2 : Atome de Na (index 3) ----- \n")

symmop2 = symmops[i_symmop2 - 1]
print(symmop2)

print("Les coordonnées initial de l'atome sont")
pos_init = conv_struc.sites[i_atom2 -1].frac_coords
print(pos_init,"\n")

print("Apres l'opération de symmétrie, ces coordonnées sont")
pos_final = symmop2.operate(pos_init)
print(pos_final,"\n")


print("Pour cette deuxième opération de symmétrie, on observe une rotation hélicoïdale de rotation pi et de translation 1. La notation d'un telle symmétrie est un 2 avec comme indice 1 : 2_1.")

view2 = quick_view(conv_struc, "packed", conventional = True)
display(view2)


view2.script('draw SYMOP ' + str(i_symmop2 + 1) + ' {atomno = ' + str(i_atom2) + '}')




----- Symmétrie 2 : Atome de Na d'index 3 ----- 

Rot:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Les coordonnées initial de l'atome sont
[0.25 0.75 0.75] 

Apres l'opération de symmétrie, ces coordonnées sont
[-0.75  0.25 -0.75] 

Pour cette deuxième opération de symmétrie, on observe une rotation hélicoïdale de rotation pi et de translation 1. La notation d'un telle symmétrie est un 2 avec comme indice 1 : 2_1.


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [15]:
#Symmétrie 3


i_atom3 = 11
i_symmop3 = 5

print("----- Symmétrie 3 : Atome de Na (index 11) ----- \n")

symmop3 = symmops[i_symmop3 - 1]
print(symmop3)

print("Les coordonnées initial de l'atome sont")
pos_init = conv_struc.sites[i_atom3 -1].frac_coords
print(pos_init,"\n")

print("Apres l'opération de symmétrie, ces coordonnées sont")
pos_final = symmop3.operate(pos_init)
print(pos_final,"\n")

print("Pour cette troisième cellule, on observe une symmétrie de réflexion par rapport au plan (001).")

view3 = quick_view(conv_struc, "packed", conventional = True)
display(view3)




view3.script('draw SYMOP ' + str(i_symmop3 + 1) + ' {atomno = ' + str(i_atom3) + '}')

----- Symmétrie 3 : Atome de Na d'index 11 ----- 

Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Les coordonnées initial de l'atome sont
[0.5 0.  0.5] 

Apres l'opération de symmétrie, ces coordonnées sont
[-0.5  0.   0.5] 

Pour cette troisième cellule, on observe une symmétrie de réflexion par rapport au plan (001).


JsmolView(layout=Layout(align_self='stretch', height='400px'))