# Tâche 5 : SYMMETRY
Vandescure Lenny (30752100)

In [11]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display

In [12]:
mp_key = "0DGGEC1I1pS8KvdIsdLZpSI8D4eSE7ux"
mp_id = "mp-648"

In [13]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id) 

conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure() 
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations() 



Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

In [14]:


print("visualisation du Na2S :")

view = quick_view(conv_struc, "packed", conventional = True)
display(view)
view.script('rotate on')



visualisation du Na2S :


JsmolView(layout=Layout(align_self='stretch', height='400px'))

## Première symétrie

In [15]:
# Symetrie 1

i_atom1 = 7
i_symmop1 = 2

print("----- Symétrie 1 : Atome de Na (index 7) ----- \n")

symmop1 = symmops[i_symmop1]
print(symmop1)

print("\n avec Rot la matrice de rotation et tau le vecteur de translation \n")

print("Les coordonnées initiales de l'atome sont")
pos_init = conv_struc.sites[i_atom1 -1].frac_coords
print(pos_init,"\n")

print("Après l'opération de symétrie, ces coordonnées sont")
pos_final = symmop1.operate(pos_init)
print(pos_final,"\n")


view1 = quick_view(conv_struc, "packed", conventional = True)
display(view1)


view1.script('draw SYMOP ' + str(i_symmop1 + 1) + ' {atomno = ' + str(i_atom1) + '}')


----- Symétrie 1 : Atome de Na (index 7) ----- 

Rot:
[[ 0. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]

 avec Rot la matrice de rotation et tau le vecteur de translation 

Les coordonnées initiales de l'atome sont
[0.75 0.75 0.25] 

Apres l'opération de symétrie, ces coordonnées sont
[-0.75  0.75  0.25] 



JsmolView(layout=Layout(align_self='stretch', height='400px'))

La matrice de rotation effectue une rotation de 90 degrés autour de l'axe c. Elle représente donc une symétrie de rotation d'ordre 4 (C4).
On peut observer que le déterminant de cette matrice est unitaire. Cette opération conserve donc la chiralité.

Il s'agit d'une opération de symétrie ponctuelle.

## Seconde symétrie

In [16]:
# Symétrie 2

i_atom2 = 3
i_symmop2 = 130

print("----- Symétrie 2 : Atome de Na (index 3) ----- \n")

symmop2 = symmops[i_symmop2 - 0]
print(symmop2)

print("\n avec Rot la matrice de rotation et tau le vecteur de translation \n")

print("Les coordonnées initiales de l'atome sont")
pos_init = conv_struc.sites[i_atom2 -1].frac_coords
print(pos_init,"\n")

print("Après l'opération de symétrie, ces coordonnées sont")
pos_final = symmop2.operate(pos_init)
print(pos_final,"\n")


view2 = quick_view(conv_struc, "packed", conventional = True)
display(view2)


view2.script('draw SYMOP ' + str(i_symmop2 + 1) + ' {atomno = ' + str(i_atom2) + '}')




----- Symétrie 2 : Atome de Na (index 3) ----- 

Rot:
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0. -1.  0.]]
tau
[0.5 0.  0.5]

 avec Rot la matrice de rotation et tau le vecteur de translation 

Les coordonnées initiales de l'atome sont
[0.25 0.75 0.75] 

Apres l'opération de symétrie, ces coordonnées sont
[ 0.75  0.75 -0.25] 



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Pour cette deuxième cellule, on observe une opération hélicoïdale selon un axe parallèle à a et une rotation pi/2. De plus, le déterminant de la matrice de rotation est unitaire ce qui justifie la conservation de la chiralité pour cette opération.

Il s'agit d'une opération de symétrie spatiale.

## Troisième symétrie

In [17]:
#Symétrie 3


i_atom3 = 11
i_symmop3 = 5

print("----- Symétrie 3 : Atome de Na (index 11) ----- \n")

symmop3 = symmops[i_symmop3 - 0]
print(symmop3)

print("\n avec Rot la matrice de rotation et tau le vecteur de translation \n")

print("Les coordonnées initiales de l'atome sont")
pos_init = conv_struc.sites[i_atom3 -1].frac_coords
print(pos_init,"\n")

print("Après l'opération de symétrie, ces coordonnées sont")
pos_final = symmop3.operate(pos_init)
print(pos_final,"\n")


view3 = quick_view(conv_struc, "packed", conventional = True)
display(view3)




view3.script('draw SYMOP ' + str(i_symmop3 + 1) + ' {atomno = ' + str(i_atom3) + '}')

----- Symétrie 3 : Atome de Na (index 11) ----- 

Rot:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]

 avec Rot la matrice de rotation et tau le vecteur de translation 

Les coordonnées initiales de l'atome sont
[0.5 0.  0.5] 

Apres l'opération de symétrie, ces coordonnées sont
[ 0.5  0.  -0.5] 



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Pour cette troisième cellule, on observe une symétrie de réflexion par rapport au plan (001). On remarque également que la déterminant de la matrice de rotation est unitaite au signe près ce qui inverse donc sa chiralité.

Il s'agit d'une opération de symétrie ponctuelle.